version: 2

updates:

# Update to npm packages
  - package-ecosystem: "npm"
    # Everything in the root directory
    directory: "/"
    schedule:
      interval: "daily"

  # Update to composer packages
  - package-ecosystem: "composer"
    commit-message:
      include: "scope"
      prefix: "composer"
    directory: "/"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    versioning-strategy: "increase"

  # Workflow files stored in the
  - package-ecosystem: "github-actions"
    commit-message:
      include: "scope"
      prefix: "github-actions"
    # default location of `.github/workflows`
    directory: "/"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"